SKILLS = [
    {"id": "python", "label": "Python"},
    {"id": "javascript", "label": "JavaScript"},
    {"id": "typescript", "label": "TypeScript"},
    {"id": "java", "label": "Java"},
    {"id": "go", "label": "Go"},
    {"id": "rust", "label": "Rust"},
    {"id": "php", "label": "PHP"},
    {"id": "ruby", "label": "Ruby"},
    {"id": "swift", "label": "Swift"},
    {"id": "kotlin", "label": "Kotlin"},
    {"id": "react", "label": "React"},
    {"id": "vue", "label": "Vue"},
    {"id": "angular", "label": "Angular"},
    {"id": "node", "label": "Node.js"},
    {"id": "nextjs", "label": "Next.js"},
    {"id": "django", "label": "Django"},
    {"id": "flask", "label": "Flask"},
    {"id": "fastapi", "label": "FastAPI"},
    {"id": "spring", "label": "Spring"},
    {"id": "rails", "label": "Rails"},
    {"id": "sql", "label": "SQL"},
    {"id": "postgres", "label": "PostgreSQL"},
    {"id": "mongodb", "label": "MongoDB"},
    {"id": "redis", "label": "Redis"},
    {"id": "aws", "label": "AWS"},
    {"id": "docker", "label": "Docker"},
    {"id": "kubernetes", "label": "Kubernetes"},
    {"id": "terraform", "label": "Terraform"},
    {"id": "devops", "label": "DevOps"},
    {"id": "machine-learning", "label": "Machine Learning"},
    {"id": "data-science", "label": "Data Science"},
    {"id": "android", "label": "Android"},
    {"id": "ios", "label": "iOS"},
    {"id": "flutter", "label": "Flutter"},
    {"id": "graphql", "label": "GraphQL"},
    {"id": "elasticsearch", "label": "Elasticsearch"},
    {"id": "linux", "label": "Linux"},
    {"id": "git", "label": "Git"},
    {"id": "html", "label": "HTML"},
    {"id": "css", "label": "CSS"},
]

SKILL_IDS = {skill["id"] for skill in SKILLS}

SKILL_LABELS = {skill["id"]: skill["label"] for skill in SKILLS}
